name: Deploy Next.js application

on:
  push:
    branches: 
      - deploy-with-docker-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env && echo "NEXT_PUBLIC_URL=${{secrets.NEXT_PUBLIC_URL}}" >> .env && echo "AWS_BUCKET_NAME=${{secrets.AWS_BUCKET_NAME}}" >> .env && echo "AWS_BUCKET_REGION=${{secrets.}}" >> .env