name: Deploy Next.js application

on:
  push:
    branches: 
      - deploy-with-docker-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env && echo "NEXT_PUBLIC_URL=${{secrets.NEXT_PUBLIC_URL}}" >> .env && echo "AWS_BUCKET_NAME=${{secrets.AWS_BUCKET_NAME}}" >> .env && echo "AWS_BUCKET_REGION=${{secrets.AWS_BUCKET_REGION}}" >> .env && echo "AWS_ACCESS_KEY=${{secrets.AWS_ACCESS_KEY}}" >> .env && echo "AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}" >> .env && echo "NEXT_PUBLIC_AWS_BUCKET_URL=${{secrets.NEXT_PUBLIC_AWS_BUCKET_URL}}" >> .env && echo "SECRET_STRIPE_KEY=${{secrets.SECRET_STRIPE_KEY}}" >> .env && echo "NEXT_PUBLIC_PUBLISHABLE_STRIPE_KEY=${{secrets.NEXT_PUBLIC_PUBLISHABLE_STRIPE_KEY}}" >> .env
      - name: Build docker image
        run: docker build -t atozionwebdesign/ecommerce-beauty .
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Publish image to docker hub
        run: docker push atozionwebdesign/ecommerce-beauty:latest

  deploy:
        